// examples/react/App.tsx
import { AgentUIAnnotation, useAgentUIAnnotation } from 'agent-ui-annotation/react';

export default function App() {
  const { ref, activate, copyOutput } = useAgentUIAnnotation();

  return (
    <>
      <h1>Agent UI Annotation - React</h1>
      <button onClick={activate}>Activate</button>
      <button onClick={() => copyOutput()}>Copy Output</button>

      <AgentUIAnnotation
        ref={ref}
        theme="auto"
        outputLevel="standard"
        onAnnotationCreate={(a) => console.log('Created:', a)}
        onCopy={(content) => console.log('Copied:', content)}
      />
    </>
  );
}

// examples/vue/App.vue
<script setup lang="ts">
import { AgentUIAnnotation, useAgentUIAnnotation } from 'agent-ui-annotation/vue';

const { ref: annotationRef, activate, copyOutput } = useAgentUIAnnotation();

const onAnnotationCreate = (annotation: any) => console.log('Created:', annotation);
const onCopy = (content: string) => console.log('Copied:', content);
</script>

<template>
  <h1>Agent UI Annotation - Vue</h1>
  <button @click="activate">Activate</button>
  <button @click="copyOutput()">Copy Output</button>

  <AgentUIAnnotation
    ref="annotationRef"
    theme="auto"
    output-level="standard"
    @annotation-create="onAnnotationCreate"
    @copy="onCopy"
  />
</template>
