// examples/svelte/components/CTAButton.svelte
<script lang="ts">
  export let label: string = 'Get Started';
</script>

<button class="cta-button">{label}</button>

<style>
  .cta-button {
    padding: 10px 16px;
    border-radius: 8px;
    border: none;
    background: #5b7cfa;
    color: white;
    font-weight: 600;
    cursor: pointer;
  }
</style>

// examples/vue/components/CTAButton.vue
<template>
  <button class="cta-button">{{ label }}</button>
</template>

<script setup lang="ts">
defineProps<{ label: string }>();
</script>

<style scoped>
.cta-button {
  padding: 10px 16px;
  border-radius: 8px;
  border: none;
  background: #5b7cfa;
  color: white;
  font-weight: 600;
  cursor: pointer;
}
</style>
