// examples/svelte/App.svelte
<script lang="ts">
  import { AgentUIAnnotation } from 'agent-ui-annotation/svelte';
  import type { Annotation } from 'agent-ui-annotation/svelte';

  let annotation: AgentUIAnnotation;

  const onAnnotationCreate = (a: Annotation) => console.log('Created:', a);
  const onCopy = (content: string) => console.log('Copied:', content);
</script>

<h1>Agent UI Annotation - Svelte</h1>
<button onclick={() => annotation.activate()}>Activate</button>
<button onclick={() => annotation.copyOutput()}>Copy Output</button>

<AgentUIAnnotation
  bind:this={annotation}
  theme="auto"
  outputLevel="standard"
  {onAnnotationCreate}
  {onCopy}
/>

// examples/react/App.tsx
import { AgentUIAnnotation, useAgentUIAnnotation } from 'agent-ui-annotation/react';

export default function App() {
  const { ref, activate, copyOutput } = useAgentUIAnnotation();

  return (
    <>
      <h1>Agent UI Annotation - React</h1>
      <button onClick={activate}>Activate</button>
      <button onClick={() => copyOutput()}>Copy Output</button>

      <AgentUIAnnotation
        ref={ref}
        theme="auto"
        outputLevel="standard"
        onAnnotationCreate={(a) => console.log('Created:', a)}
        onCopy={(content) => console.log('Copied:', content)}
      />
    </>
  );
}
