// examples/vue/components/HeroSection.vue
<template>
  <section class="hero">
    <h2>Ship UI changes faster</h2>
    <p>Annotate real UI elements with precision and context.</p>
    <CTAButton label="Start annotating" />
  </section>
</template>

<script setup lang="ts">
import CTAButton from './CTAButton.vue';
</script>

<style scoped>
.hero {
  padding: 16px;
  border: 1px solid #333;
  border-radius: 8px;
}
</style>

// examples/svelte/components/HeroSection.svelte
<script lang="ts">
  import CTAButton from './CTAButton.svelte';
</script>

<section class="hero">
  <h2>Ship UI changes faster</h2>
  <p>Annotate real UI elements with precision and context.</p>
  <CTAButton label="Start annotating" />
</section>

<style>
  .hero {
    padding: 16px;
    border: 1px solid #333;
    border-radius: 8px;
  }
</style>
